# Конфигурация кэш-зоны на диске Nginx
# keys_zone=reports_cache:10m выделяет 10МБ под ключи (хватит на ~80 000 метаданных)
# max_size=1g ограничивает максимальный объем кэша на диске в 1 Гигабайт
# inactive=24h удаляет файлы, к которым не обращались сутки
proxy_cache_path /var/cache/nginx/cdn_zone levels=1:2 keys_zone=reports_cache:10m max_size=1g inactive=24h use_temp_path=off;

server {
    listen 80;
    server_name localhost;

    # Логирование кэш-статусов (HIT/MISS/BYPASS) для отладки
    access_log /var/log/nginx/cdn_access.log;

    location /reports/ {
        # Внутреннее имя S3-хранилища в Docker-сети и целевой бакет
        proxy_pass http://minio:9000/bionicpro-reports/;
        
        # Включаем кэширование статики
        proxy_cache reports_cache;
        proxy_cache_key "$uri$is_args$args"; # Строгий ключ кэша с учетом параметров периода
        
        # Инвалидация/Параметры хранения успешных ответов
        proxy_cache_valid 200 24h;       # Кешируем успешные отчеты на 24 часа
        proxy_cache_valid 403 404 1m;     # Быстро сбрасываем кэш ошибок (если отчет еще генерируется)

        # Полезные заголовки для фронтенда и отладки
        add_header X-Cache-Status $upstream_cache_status; # Показывает HIT или MISS
        add_header Access-Control-Allow-Origin "*";       # Разрешаем CORS скачивание статики
        
        # Маскируем внутренние S3 заголовки ответа Minio
        proxy_hide_header x-amz-request-id;
        proxy_hide_header x-amz-id-2;
        proxy_hide_header Server;

        # Настройки таймаутов, чтобы CDN не зависал при первом чтении тяжелых файлов
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }
}